name: "Print Event SHAs"
description: "Run ARMOR tool"
author: "LinuxIntegration"
branding:
  icon: "align-left"
  color: "blue"

inputs:
  event-name:
    description: "github.event_name from the caller"
    required: true
  head-sha:
    description: "Head SHA for the event (PR head or push after)"
    required: true
  base-sha:
    description: "Base SHA for the event (PR base or push before)"
    required: false
    default: ""
  ref:
    description: "Ref associated with the event"
    required: false
    default: ""
  repo:
    description: "owner/repo of the caller"
    required: false
    default: ""
  actor:
    description: "Triggering actor (github.actor)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout base commit
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.base-sha }}
        path: base

    - name: Checkout head commit
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.head-sha }}
        path: head

    - name: Echo path in action
      shell: bash
      run: |
        echo "Base SHA: ${{ inputs.base-sha }}"
        echo "Head SHA: ${{ inputs.head-sha }}"
        BASE_PATH="$GITHUB_WORKSPACE/base"
        HEAD_PATH="$GITHUB_WORKSPACE/head"
        echo "github-base path : $BASE_PATH"
        echo "github-head path : $HEAD_PATH"

    - name: print gcc version
      shell: bash
      run: |

    - name: Verify gcc version and  Docker installation
      shell: bash
      run: |
        gcc --version
        docker --version

    - name: Build docker image
      shell: bash
      run: |
        docker build -t armor_tool:latest -f ${{ github.action_path }}/Dockerfile .

    - name: Get changed files
      id: changed-files
      shell: bash
      run: |
        cd head
        git fetch origin ${{ inputs.base-sha }}
        git diff --name-only ${{ inputs.base-sha }} ${{ inputs.head-sha }} > $GITHUB_WORKSPACE/changed_files.txt
        echo "Changed files:"
        cat $GITHUB_WORKSPACE/changed_files.txt

    - name: Parse YAML for headers
      id: parse-yaml
      shell: bash
      run: |
        YAML_FILE="$GITHUB_WORKSPACE/public_headers/armor_config.yaml"
        if [[ -f "$YAML_FILE" ]]; then
          echo "Parsing $YAML_FILE"
          HEADERS=$(yq '.branches.main.headers[]' "$YAML_FILE")
          echo "$HEADERS" > $GITHUB_WORKSPACE/headers.txt
          echo "Headers from YAML:"
          cat $GITHUB_WORKSPACE/headers.txt
        else
          echo "YAML file not found!"
          exit 1
        fi


    - name: Find intersection of changed files and headers
      id: intersection
      shell: bash
      run: |
        INTERSECT=$(grep -Fxf $GITHUB_WORKSPACE/headers.txt $GITHUB_WORKSPACE/changed_files.txt || true)
        echo "$INTERSECT" > $GITHUB_WORKSPACE/updated_headers_PR.txt
        if [[ -n "$INTERSECT" ]]; then
          echo "Intersection found:"
          cat $GITHUB_WORKSPACE/updated_headers_PR.txt
          echo "has-intersection=true" >> "$GITHUB_OUTPUT"
        else
          echo "No intersection found."
          : > "$GITHUB_WORKSPACE/updated_headers_PR.txt"
          echo "has-intersection=false" >> "$GITHUB_OUTPUT"
        fi

    - name: build armor tool
      shell: bash
      run: |
        ACTION_DIR=${{ github.action_path }}
        docker run -i --rm \
          --user $(id -u):$(id -g) \
          --workdir="$ACTION_DIR" \
          -v "$ACTION_DIR":"$ACTION_DIR" \
          -e ACTION_DIR="$ACTION_DIR" \
          armor_tool:latest bash -c '
            set -euo pipefail
            chmod +x ./api_compat_check.sh
            ./api_compat_check.sh --package
            ARMOR_BINS_PATH="$ACTION_DIR/build/armor"
          '

    - name: Run ARMOR per header (collect outputs)
      if: steps.intersection.outputs.has-intersection == 'true'
      id: run-armor
      shell: bash
      env:
        HEAD_SHA:   ${{ inputs.head-sha }}
        BASE_SHA:   ${{ steps.base-ref.outputs.base }}
        # Optional armor tuning:
        # HEADER_DIR: "include/api"           # if your headers list are basenames
        REPORT_FORMAT: "json"               # produces html + json
        # INCLUDE_PATHS: "-I include -I third_party/include"
        # MACRO_FLAGS: "-DUSE_FOO -DVALUE=1"
        LOG_LEVEL: "INFO"
        DUMP_AST_DIFF: "true"
      run: |
        BASE_PATH="$GITHUB_WORKSPACE/base"
        HEAD_PATH="$GITHUB_WORKSPACE/head"
        INTERSECTION_HEADERS_PATH="$GITHUB_WORKSPACE/updated_headers_PR.txt"
        ARMOR_BINS_PATH="${{ github.action_path }}/build/armor"
        chmod +x "${{ github.action_path }}/action_script/run_armor.sh"
        "${{ github.action_path }}/action_script/run_armor.sh" "$BASE_PATH" "$HEAD_PATH" "$INTERSECTION_HEADERS_PATH" "$ARMOR_BINS_PATH"

        OUT_ROOT="$(cat "$GITHUB_WORKSPACE/.armor_out_root")"
        echo "out-root=$OUT_ROOT" >> "$GITHUB_OUTPUT"

    - name: Upload updated_headers_PR artifact
      if: steps.intersection.outputs.has-intersection == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: updated_headers_PR
        path: ${{ github.workspace }}/updated_headers_PR.txt
    
    - name: Upload all armor outputs (artifact)
      if: steps.intersection.outputs.has-intersection == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: armor-output-${{ inputs.head-sha }}
        path: ${{ steps.run-armor.outputs.out-root }}
        if-no-files-found: warn
